### PR TITLE
add contact us link to footer, fix email address var in error messages

### LINKED ISSUE #578: add "contact us" link to footer
I don't think it's worth the effort to add a ZenDesk widget (which we can't customize easily). 

I think a simple mailto link will be sufficient, although it won't work well for gmail users.

### PR DESCRIPTION
**Pull request by adorsk**
#### What are the relevant tickets?
Fixes #578.

#### What's this PR do?
1. Adds a 'Contact Us' link to the footer.
2. Fixes a bad key name for support email in `errorMessages`

#### How should this be manually tested?
1. Ensure that there is a 'Contact Us' link in the footer that is a mailto link to the support email.

### CODE REVIEW

File: static/js/components/Footer_test.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+  }
+
+  it("has 'Contact Us' link", () => {
+    SETTINGS.support_email_address = "some@email.address"
+    const wrapper = renderComponent()
+    const link = wrapper.find("a.contact-us")
+    assert.equal(link.text(), "Contact Us")
+    assert.equal(link.prop("href"), `mailto:${SETTINGS.support_email_address}`)
+  })
+
```
Comment (aliceriot) [inline static/js/components/Footer_test.js]: blank line

File: static/js/components/errorMessages.js [hunk 2]
```diff
@@ -6,7 +6,7 @@ import ErrorMessage from "./ErrorMessage"
 
 export const UnableToLoadData = () => {
   // $FlowFixMe
```
Comment (aliceriot) [inline static/js/components/errorMessages.js]: I think the `$FlowFixMe` here can be removed (I tried out removing it locally on my machine and flow passes ok with the change you made)

File: static/js/components/Footer_test.js [hunk 3]
```diff
@@ -0,0 +1,23 @@
+// @flow
+/* global SETTINGS: false */
+import React from "react"
+import { shallow } from "enzyme"
+import { assert } from "chai"
+
+import Footer from "./Footer"
+
+describe("Footer", () => {
+
```
Comment (aliceriot) [inline static/js/components/Footer_test.js]: another blank one! :)
