### PR TITLE
Fix scrollbar issue when dialog is closed.

### LINKED ISSUE #213: Bug: After opening a modal, scrolling no longer works
To reproduce:

Go to the Video Details page and scroll down. 
Click either "Edit" or "Share".
Close the modal, either by clicking close or cancel, or by clicking outside the modal.
Try to scroll up, and scrolling does not work.

I found this bug on Mac/Chrome.

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Fixes #213 

#### What's this PR do?
Destroys MDC dialogs instead of closing them, and recreates them again as necessary.

#### How should this be manually tested?
- On a video detail page:
  - Scroll down, click the 'Edit' button, make changes, and click the 'Save' button.  The browser scrollbar should still work. Repeat multiple times to ensure the dialog continues to open and close properly.
  - Click the 'Share' button to open the dialog, then close it.  Make sure scrolling still works. Repeat multiple times.

- On a collection detail page with 2+ videos:
  - Click the edit button of at least 2 videos, make changes, save, then repeat again. Make sure the scrollbar still works and the dialogs still function properly.
  - Repeat the above with the video share buttons.

### CODE REVIEW

File: static/js/components/material/Dialog.js [hunk 1]
```diff
@@ -45,13 +47,14 @@ export default class Dialog extends React.Component {
...
+        if (this.dialog) {
           this.dialog.show();
-        } else {
-          this.dialog.close();
         }
+      } else if (this.dialog) {
+        this.dialog.destroy();
       }
     }
   }
```
Comment (gsidebo) [inline static/js/components/material/Dialog.js]: I tinkered with this a little locally to see how the MDCDialog object behaves. We can make this a bit more concise with something like this:

```javascript
  showMdc() {
    if (this.dialog) {
      this.dialog.show();
    }
  }

  destroyMdc() {
    if (this.dialog) {
      this.dialog.destroy();
    }
  }

  componentDidMount() {
    this.createDialog();
    if (this.props.show) this.showMdc();
  }

  componentWillUnmount() {
    this.destroyMdc();
  }

  componentWillReceiveProps(nextProps: DialogProps) {
    if (this.props.open !== nextProps.open) {
      if (nextProps.open) {
        this.showMdc();
      } else {
        this.destroyMdc();
      }
    }
  }
```

Comment (mbertrand) [reply static/js/components/material/Dialog.js]: OK

File: static/js/components/material/Dialog.js [hunk 2]
```diff
@@ -22,36 +22,47 @@ export default class Dialog extends React.Component {
...
-    if (this.dialog) {
-      if (this.props.open !== nextProps.open) {
-        if (nextProps.open) {
-          this.dialog.show();
-        } else {
-          this.dialog.close();
-        }
+    if (this.props.open !== nextProps.open) {
+      if (nextProps.open) {
+        this.createDialog();
```
Comment (gsidebo) [inline static/js/components/material/Dialog.js]: I tested this without `this.createDialog()` and it seemed to work. Are you sure we need this?

Comment (mbertrand) [reply static/js/components/material/Dialog.js]: Guess not, I could have sworn that I wasn't able to reopen dialogs without it earlier today, but now it does seem to be working fine without it.
